services:
  Alpdesk\AlpdeskClasses\Listener\HooksListener:
    arguments:
      - '@contao.routing.scope_matcher'
      - '@request_stack'
    tags:
      - { name: contao.hook, hook: getArticle, method: onGetArticle, priority: 0 }
      - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
